### ISSUE TITLE
Missing Directory Support

### ISSUE THREAD

**Issue by ralph-dev** [MLH-Fellowship/0.2.1-readme-dirs#17]
WARNING: I am not trying to classify these folders by project or else it defeats the whole purpose of our application. This list is just to reference where these came from (The descriptions should apply globally and not be project-specific)
----
??? = Confused what right description is
X | Y = Name can have two naming conventions
----
StackOverFlow Suggestions

src/: "source" files to build and develop the project. This is where the original source files are located, before being compiled into fewer files to dist/, public/ or build/.
distributable/ | dist/: "distribution", the compiled code/library, also named public/ or build/. The files meant for production or public use are usually located here.
assets/: static content like images, video, audio, fonts etc.
lib/: external dependencies (when included directly).
test/: the project's tests scripts, mocks, etc.
node_modules/: includes libraries and dependencies for JS packages, used by Npm.
vendor/: includes libraries and dependencies for PHP packages, used by Composer.
bin/: files that get added to your PATH when installed.

**React**
fixtures/ - Mock Objects???

**Docsify**
.vscode/ - [Visual Studio Code](https://code.visualstudio.com/) IDE Editor Settings

**Babel**
.circleci/ - [Circle CI](https://circleci.com/) is a Continous Integration Platform
.codesandbox/ - [CodeSandbox](https://codesandbox.io/) is an Online IDE
.github/ - [Github Supported Markdown Files](https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests) like Changelogs, Issue Templates etc
packages/ - A list of Packages that this repository maintains
codemods/ - An Automatic Way to conduct Migrations of Codebases to new formats

**Sentry**
__mocks__/@sentry

**React-Native**

Android/  - Android Native Code Lives
IOS/ - IOS Native Code Lives
IntegrationTests | e2e/ - End to End Integration Tests
bots/ - Code Analysis Bots that act like Repo Watchers
flow/ - Where Code Types are kept (Similiar to TypeScript's Types folder)
jest/ - JavaScript Testing Framework (Where Tests are kept)
keystores/ - Android Debug & Release Keystores for Playstore Deployments

Atomic Design Principles | https://atomicdesign.bradfrost.com/

atoms/  - Single Layer Components
molecules/ - Collection of Atom Components to make a complex component
organisms/ - Assemblies of molecules functioning together as a unit
templates/ - Page Level Objects that define the Layout and Structure of a Page
pages/ - Specific Instances of Filled In Contentful Templates for a Complete Visual

**Graphl API**
_Definitions could be more clear but at least to have something_
/
|-- controllers   # Controllers, used to resolve GraphQL fields.
|-- errors        # Error classes thrown.
|-- gates         # Permission gates, used for permission checking.
|-- graphql       # GraphQL definitions.
    |-- enums     # Enum definitions.
    |-- inputs    # Input definitions.
    |-- types     # Type definitions.
|-- middlewares   # Express.js middlewares.
|-- migrations    # Migration scripts, useful for production, not needed if you run from a freash start.
|-- models        # Database models.
|-- providers     # Service providers.
|-- resources     # Text resources.
|-- rules         # Permission rules, these are detailed rules to be used within gates.
|-- scripts       # Setup scripts etc.
|-- util          # Utilities.
|-- validators    # Validators, used to validate inputes.

Other
Cypress/ - A Front-End JavaScript Testing Framework

**Comment by nchaloult** [comment]
Most of the directory descriptions listed above got knocked out in #31 . We decided not to close this issue yet, though, in case we all think of more common directory types to support at the last minute.
