### ISSUE TITLE
Write a more helpful README

### ISSUE THREAD

**Issue by nchaloult** [MLH-Fellowship/0.2.1-readme-dirs#2]
Right now, our project's README is the default one generated for us by the `create-react-app` utility. I'm thinking that we should scrap our current README & brainstorm ideas for what relevant information we should include in a new README.

When I think about our new README's contents, the first things that come to my mind are:

* Some kind of GIF/screenshot of the UI, or of the app in action
    * So people can quickly get an idea of what this project is and how it works
* Description / Motivation section
    * What problem are we trying to solve?
    * Why is this problem worth solving? In other words, if we solve this problem, who will benefit from our solution?
    * What are we building, or what have we built?
* Technology Breakdown
    * What tools & technologies did we use?
        * What purpose is each of those technologies serving?
            * For example, we've used React to build our front-end web application
        * For some of our choices, it might be worth writing a couple of sentences about why we chose them as opposed to some popular alternatives
        * We should highlight which of our technologies were introduced to us during our hackathon kickoff

This new README might be one of the last things that we work on during this hackathon, but I thought it was worthwhile to go ahead and create an issue about it now so that it stays on our minds.

**Comment by nchaloult** [comment]
@ralph-dev made significant progress on our README's contents. As a team, we need to review what he's written and decide if there is anything that isn't present that we should add.

**Comment by ralph-dev** [comment]
@mohammedsahl @nchaloult The only thing I can think of left is a GIF of the application!

**Comment by ralph-dev** [comment]
@mohammedsahl Can you upload the gif to the README
