### ISSUE TITLE
Architecture for DeleteQueue with Undo System

### ISSUE THREAD

**Issue by ralph-dev** [MLH-Fellowship/0.2.1-readme-dirs#28]
_This architecture proposal is just for the implementation of Tree Core ability to delete specific parts of the tree and have it re-appear with an undo button_

Requirements
- Support Deletion of any Line on the Tree Core
- Support Undo of most recent deletion on Tree Core
- Support Deletion of entire DepthLevel ( Folder )
- Support Undo of entire DepthLevel ( Folder )

We can implement a variable that holds a list of Tree Core Objects in FIFO format (Queue).

We can delete any line and push it into the DeleteQueue.
We can undo any line by popping it out of the DeleteQueue.

We can delete an entire depth level by filtering through the Tree Core for a specific depth level.
We can undo an entire depth level deletion by filtering through the DeleteQueue for a specific depth Level.

**Comment by nchaloult** [comment]
What are your plans for building UI elements around this change?

**Comment by ralph-dev** [comment]
I haven't really thought too far ahead in that area but I was thinking along the lines of Visual Studio Code.

Deleting a file or Level would collapse the div and provide a red triangle on the right side for adding it back. For general undos people would have to CTRL+Z.

This will support all cases of deletion, 1 or Many although might require the deletion of DeleteQueue and just an update to Tree Core... I'll have to think about this. Great Question!
